// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';
import {utils} from '../models';

export function CheckLogin(arg1:controller.User):Promise<utils.Resp>;

export function CreateCountDown(arg1:controller.CountDown):Promise<utils.Resp>;

export function DeleteCountDown(arg1:number):Promise<utils.Resp>;

export function GetCountDown():Promise<utils.Resp>;

export function Greet(arg1:string):Promise<string>;

export function Register(arg1:controller.User):Promise<utils.Resp>;
